export const TOUR_TARGETS = {
  common: {
    modalClose: 'modal.close',
  },
  sales: {
    panel: 'sales.panel',
    filters: 'sales.filters',
    filtersSearch: 'sales.filters.search',
    table: 'sales.table',
    primaryAction: {
        desktop: 'sales.primaryAction.desktop',
        mobile: 'sales.primaryAction.mobile',
    },
    kpis: 'sales.kpis',
    hold: 'sales.hold',
    export: 'sales.export',
    modal: {
      search: 'sales.modal.search',
      products: 'sales.modal.products',
      cart: 'sales.modal.cart',
      nextToClient: 'sales.modal.nextToClient',
      nextToPayment: 'sales.modal.nextToPayment',
      confirm: 'sales.modal.confirm',
      clientSelect: 'sales.modal.clientSelect',
      clientInfo: 'sales.modal.clientInfo',
      paymentMethods: 'sales.modal.paymentMethods',
      discount: 'sales.modal.discount',
      receipt: 'sales.modal.receipt',
    },
  },
  nav: {
    sidebar: 'nav.sidebar.desktop',
    drawer: 'nav.drawer.mobile',
    bottom: 'nav.bottom.mobile',
  },
  customers: {
    panel: 'customers.panel',
    filters: 'customers.filters',
    table: 'customers.table',
    primaryAction: {
        desktop: 'customers.primaryAction.desktop',
        mobile: 'customers.primaryAction.mobile',
    },
    search: 'customers.search',
    listItem: 'customers.listItem',
    balance: 'customers.balance',
    tags: 'customers.tags',
    creditLimit: 'customers.creditLimit',
    history: 'customers.history',
    payment: 'customers.payment',
    whatsappBtn: 'customers.whatsappBtn',
    address: 'customers.address',
    filterInactive: 'customers.filterInactive',
    detail: 'customers.detail',
    debtList: 'customers.debtList',
    modal: {
      form: 'customers.modal.form',
      confirm: 'customers.modal.confirm',
    },
  },
  payments: {
    panel: 'payments.panel',
    filters: 'payments.filters',
    search: 'payments.search',
    kpis: 'payments.kpis',
    table: 'payments.table',
    primaryAction: {
        desktop: 'payments.primaryAction.desktop',
        mobile: 'payments.primaryAction.mobile',
    },
    tabs: {
      overdue: 'payments.tabs.overdue',
      all: 'payments.tabs.all',
    },
    list: 'payments.list',
    modal: {
      clientSearch: 'payments.modal.clientSearch',
      clientList: 'payments.modal.clientList',
      details: 'payments.modal.details',
      next: 'payments.modal.next',
      confirm: 'payments.modal.confirm',
    }
  },
  dashboard: {
    panel: 'dashboard.panel',
    kpis: 'dashboard.kpis',
    charts: 'dashboard.charts',
    periodSelector: 'dashboard.periodSelector',
    comparison: 'dashboard.comparison',
    topProducts: 'dashboard.topProducts',
    alerts: 'dashboard.alerts',
    quickActions: 'dashboard.quickActions',
    tabs: {
      hoy: 'dashboard.tabs.hoy',
      balance: 'dashboard.tabs.balance',
      analytics: 'dashboard.tabs.analytics',
      reminders: 'dashboard.tabs.reminders',
    },
    analytics: {
      salesChart: 'dashboard.analytics.salesChart',
    },
    balance: {
      summary: 'dashboard.balance.summary',
    }
  },
  products: {
    panel: 'products.panel',
    primaryAction: 'products.primaryAction',
    table: 'products.table',
    filters: 'products.filters',
    search: 'products.search',
    export: 'products.export',
    kpis: 'products.kpis',
    tabs: {
      catalog: 'products.tabs.catalog',
      inventory: 'products.tabs.inventory',
      pricing: 'products.tabs.pricing',
    },
    inventory: {
      table: 'products.inventory.table',
      quickAdjust: 'products.inventory.quickAdjust',
    },
    pricing: {
      table: 'products.pricing.table',
      formula: 'products.pricing.formula',
    },
    modal: {
      form: 'products.modal.form',
      confirm: 'products.modal.confirm',
    },
  },
  orders: {
    panel: 'orders.panel',
    board: 'orders.board',
    filters: 'orders.filters',
    primaryAction: 'orders.primaryAction',
    card: 'orders.card',
    settings: 'orders.settings',
    duplicate: 'orders.duplicate',
    whatsapp: 'orders.whatsapp',
    export: 'orders.export',
    modal: {
      search: 'orders.modal.search',
      products: 'orders.modal.products',
      cart: 'orders.modal.cart',
      next: 'orders.modal.next',
      client: 'orders.modal.client',
      confirm: 'orders.modal.confirm',
    }
  },
  quotes: {
    panel: 'quotes.panel',
    primaryAction: 'quotes.primaryAction',
    filters: 'quotes.filters',
    table: 'quotes.table',
    modal: {
      context: 'quotes.modal.context',
      items: 'quotes.modal.items',
      confirm: 'quotes.modal.confirm',
    },
  },
  suppliers: {
    panel: 'suppliers.panel',
    primaryAction: 'suppliers.primaryAction',
    filters: 'suppliers.filters',
    table: 'suppliers.table',
    modal: {
      form: 'suppliers.modal.form',
      confirm: 'suppliers.modal.confirm',
    },
  },
  rawPurchases: {
    panel: 'raw-purchases.panel',
    primaryAction: 'raw-purchases.primaryAction',
    filters: 'raw-purchases.filters',
    table: 'raw-purchases.table',
    modal: {
      form: 'raw-purchases.modal.form',
      items: 'raw-purchases.modal.items',
      confirm: 'raw-purchases.modal.confirm',
    },
  },
  recipes: {
    panel: 'recipes.panel',
    primaryAction: 'recipes.primaryAction',
    filters: 'recipes.filters',
    table: 'recipes.table',
    modal: {
      form: 'recipes.modal.form',
      items: 'recipes.modal.items',
      confirm: 'recipes.modal.confirm',
    },
  },
  costCalculator: {
    panel: 'cost-calculator.panel',
    scope: 'cost-calculator.scope',
    materials: 'cost-calculator.materials',
    actions: 'cost-calculator.actions',
    result: 'cost-calculator.result',
  },
  expenses: {
    panel: 'expenses.panel',
    primaryAction: 'expenses.primaryAction',
    table: 'expenses.table',
    filters: 'expenses.filters',
    category: 'expenses.category',
    recurring: 'expenses.recurring',
    kpis: 'expenses.kpis',
    tabs: {
      movements: 'expenses.tabs.movements',
      recurring: 'expenses.tabs.recurring',
      payables: 'expenses.tabs.payables',
      analytics: 'expenses.tabs.analytics',
      categories: 'expenses.tabs.categories',
    },
    modal: {
      description: 'expenses.modal.description',
      amount: 'expenses.modal.amount',
      date: 'expenses.modal.date',
      category: 'expenses.modal.category',
      receipt: 'expenses.modal.receipt',
      confirm: 'expenses.modal.confirm',
    }
  },
  reports: {
    panel: 'reports.panel',
    dashboard: 'reports.catalog',
    export: 'reports.export',
    filters: 'reports.filters',
    sales: 'reports.profitability',
    inventory: 'reports.team',
    tabs: {
      sales: 'reports.tabs.sales',
      expenses: 'reports.tabs.expenses',
      profitability: 'reports.tabs.profitability',
    },
    generate: 'reports.generate',
    content: 'reports.content',
  },
  invoices: {
    panel: 'invoices.panel',
    filters: 'invoices.filters',
    summary: 'invoices.summary',
    table: 'invoices.table',
    primaryAction: 'invoices.primaryAction',
    settings: 'invoices.settings',
    receivables: 'invoices.receivables',
    sync: 'invoices.sync',
    modal: {
      form: 'invoices.modal.form',
      confirm: 'invoices.modal.confirm',
    },
  },
  invoiceReceivables: {
    panel: 'invoice-receivables.panel',
    filters: 'invoice-receivables.filters',
    summary: 'invoice-receivables.summary',
    table: 'invoice-receivables.table',
  },
  invoiceSync: {
    panel: 'invoice-sync.panel',
    summary: 'invoice-sync.summary',
    table: 'invoice-sync.table',
  },
  alerts: {
    panel: 'alerts.panel',
    list: 'alerts.list',
    filters: 'alerts.filters',
    config: 'alerts.config',
    resolve: 'alerts.resolve',
    snooze: 'alerts.snooze',
  },
  settings: {
    panel: 'settings.panel',
    profile: 'settings.profile',
    business: 'settings.business',
    personalization: 'settings.personalization',
    team: 'settings.team',
    roles: 'settings.roles',
    templates: 'settings.templates',
    membership: 'settings.membership',
    personalizationPanel: 'settings.personalization.panel',
    personalizationBase: 'settings.personalization.base',
    personalizationModules: 'settings.personalization.modules',
    personalizationMenu: 'settings.personalization.menu',
    personalizationPreview: 'settings.personalization.preview',
    whatsapp: 'settings.whatsapp',
    billing: 'settings.billing',
  },
  treasury: {
    panel: 'treasury.panel',
    primaryAction: 'treasury.primaryAction',
    filters: 'treasury.filters',
    accounts: 'treasury.accounts',
    movements: 'treasury.movements',
  },
  teamWorkspace: {
    panel: 'team.panel',
    filters: 'team.filters',
    invite: 'team.invite',
  },
  roleManagement: {
    panel: 'roles.panel',
    list: 'roles.list',
    permissions: 'roles.permissions',
  },
  rawInventory: {
    panel: 'raw-inventory.panel',
    primaryAction: 'raw-inventory.primaryAction',
    filters: 'raw-inventory.filters',
    list: 'raw-inventory.list',
    detail: 'raw-inventory.detail',
    movement: 'raw-inventory.movement',
  },
};

export const tourSel = (target: string) => `[data-tour="${target}"]`;
