export const TOUR_TARGETS = {
  common: {
    modalClose: 'modal.close',
  },
  sales: {
    panel: 'sales.panel',
    filters: 'sales.filters',
    filtersSearch: 'sales.filters.search',
    table: 'sales.table',
    primaryAction: 'sales.primaryAction',
    kpis: 'sales.kpis',
    hold: 'sales.hold',
    export: 'sales.export',
    modal: {
      search: 'sales.modal.search',
      products: 'sales.modal.products',
      cart: 'sales.modal.cart',
      nextToClient: 'sales.modal.nextToClient',
      nextToPayment: 'sales.modal.nextToPayment',
      confirm: 'sales.modal.confirm',
      clientSelect: 'sales.modal.clientSelect',
      clientInfo: 'sales.modal.clientInfo',
      paymentMethods: 'sales.modal.paymentMethods',
      discount: 'sales.modal.discount',
      receipt: 'sales.modal.receipt',
    },
  },
  customers: {
    panel: 'customers.panel',
    filters: 'customers.filters',
    table: 'customers.table',
    primaryAction: 'customers.primaryAction',
    search: 'customers.search',
    listItem: 'customers.listItem',
    balance: 'customers.balance',
    tags: 'customers.tags',
    creditLimit: 'customers.creditLimit',
    history: 'customers.history',
    payment: 'customers.payment',
    whatsappBtn: 'customers.whatsappBtn',
    address: 'customers.address',
    filterInactive: 'customers.filterInactive',
    detail: 'customers.detail',
    debtList: 'customers.debtList',
  },
  payments: {
    panel: 'payments.panel',
    filters: 'payments.filters',
    table: 'payments.table',
    primaryAction: 'payments.primaryAction',
    tabs: {
      overdue: 'payments.tabs.overdue',
      all: 'payments.tabs.all',
    },
    list: 'payments.list',
    modal: {
      clientSearch: 'payments.modal.clientSearch',
      clientList: 'payments.modal.clientList',
      details: 'payments.modal.details',
      next: 'payments.modal.next',
      confirm: 'payments.modal.confirm',
    }
  },
  dashboard: {
    panel: 'dashboard.panel',
    kpis: 'dashboard.kpis',
    charts: 'dashboard.charts',
    periodSelector: 'dashboard.periodSelector',
    comparison: 'dashboard.comparison',
    topProducts: 'dashboard.topProducts',
    alerts: 'dashboard.alerts',
    quickActions: 'dashboard.quickActions',
    tabs: {
      hoy: 'dashboard.tabs.hoy',
      balance: 'dashboard.tabs.balance',
      analytics: 'dashboard.tabs.analytics',
      reminders: 'dashboard.tabs.reminders',
    },
    analytics: {
      salesChart: 'dashboard.analytics.salesChart',
    },
    balance: {
      summary: 'dashboard.balance.summary',
    }
  },
  products: {
    panel: 'products.panel',
    primaryAction: 'products.primaryAction',
    table: 'products.table',
    filters: 'products.filters',
    search: 'products.search',
    export: 'products.export',
    kpis: 'products.kpis',
    tabs: {
      catalog: 'products.tabs.catalog',
      inventory: 'products.tabs.inventory',
      pricing: 'products.tabs.pricing',
    },
    inventory: {
      table: 'products.inventory.table',
      quickAdjust: 'products.inventory.quickAdjust',
    },
    pricing: {
      calculator: 'products.pricing.calculator',
    }
  },
  orders: {
    panel: 'orders.panel',
    board: 'orders.board',
    primaryAction: 'orders.primaryAction',
    card: 'orders.card',
    settings: 'orders.settings',
    duplicate: 'orders.duplicate',
    whatsapp: 'orders.whatsapp',
    export: 'orders.export',
    modal: {
      search: 'orders.modal.search',
      products: 'orders.modal.products',
      cart: 'orders.modal.cart',
      next: 'orders.modal.next',
      client: 'orders.modal.client',
      confirm: 'orders.modal.confirm',
    }
  },
  expenses: {
    panel: 'expenses.panel',
    primaryAction: 'expenses.primaryAction',
    table: 'expenses.table',
    filters: 'expenses.filters',
    category: 'expenses.category',
    recurring: 'expenses.recurring',
    kpis: 'expenses.kpis',
    tabs: 'expenses.tabs',
    modal: {
      description: 'expenses.modal.description',
      amount: 'expenses.modal.amount',
      date: 'expenses.modal.date',
      category: 'expenses.modal.category',
      receipt: 'expenses.modal.receipt',
      confirm: 'expenses.modal.confirm',
    }
  },
  reports: {
    panel: 'reports.panel',
    dashboard: 'reports.dashboard',
    export: 'reports.export',
    filters: 'reports.filters',
    sales: 'reports.sales',
    inventory: 'reports.inventory',
  },
  alerts: {
    panel: 'alerts.panel',
    list: 'alerts.list',
    filters: 'alerts.filters',
    config: 'alerts.config',
    resolve: 'alerts.resolve',
    snooze: 'alerts.snooze',
  },
  settings: {
    panel: 'settings.panel',
    profile: 'settings.profile',
    business: 'settings.business',
    whatsapp: 'settings.whatsapp',
    billing: 'settings.billing',
  },
};

export const tourSel = (target: string) => `[data-tour="${target}"]`;
