"""Add updated_at to payments table

Revision ID: eeddf3b6e575
Revises: 
Create Date: 2026-03-17 06:44:26.874445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'eeddf3b6e575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treasury_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_debt_payments_treasury_account_id'), ['treasury_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'treasury_accounts', ['treasury_account_id'], ['id'])

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_recurring_expense_id'), ['recurring_expense_id'], unique=False)
        batch_op.create_foreign_key(None, 'recurring_expenses', ['recurring_expense_id'], ['id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_debt_id'), ['debt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_debt_payment_id'), ['debt_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_raw_purchase_id'), ['raw_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_recurring_expense_id'), ['recurring_expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_supplier_payable_id'), ['supplier_payable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_supplier_payment_id'), ['supplier_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_treasury_account_id'), ['treasury_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'debts', ['debt_id'], ['id'])
        batch_op.create_foreign_key(None, 'treasury_accounts', ['treasury_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'raw_purchases', ['raw_purchase_id'], ['id'])
        batch_op.create_foreign_key(None, 'supplier_payments', ['supplier_payment_id'], ['id'])
        batch_op.create_foreign_key(None, 'debt_payments', ['debt_payment_id'], ['id'])
        batch_op.create_foreign_key(None, 'supplier_payables', ['supplier_payable_id'], ['id'])
        batch_op.create_foreign_key(None, 'recurring_expenses', ['recurring_expense_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treasury_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_treasury_account_id'), ['treasury_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'treasury_accounts', ['treasury_account_id'], ['id'])

    with op.batch_alter_table('raw_material_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_material_movements_raw_purchase_id'), ['raw_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_material_movements_recipe_consumption_id'), ['recipe_consumption_id'], unique=False)
        batch_op.create_foreign_key(None, 'raw_purchases', ['raw_purchase_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipe_consumptions', ['recipe_consumption_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_treasury_account_id'), ['treasury_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'treasury_accounts', ['treasury_account_id'], ['id'])

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_payments_treasury_account_id'), ['treasury_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'treasury_accounts', ['treasury_account_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_supplier_payments_treasury_account_id'))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_treasury_account_id'))

    with op.batch_alter_table('raw_material_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_raw_material_movements_recipe_consumption_id'))
        batch_op.drop_index(batch_op.f('ix_raw_material_movements_raw_purchase_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_treasury_account_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('treasury_account_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_treasury_account_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_supplier_payment_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_supplier_payable_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_recurring_expense_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_raw_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_debt_payment_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_debt_id'))

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_debts_recurring_expense_id'))

    with op.batch_alter_table('debt_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_debt_payments_treasury_account_id'))
        batch_op.drop_column('treasury_account_id')

    bind = op.get_bind()
    inspector = inspect(bind)
    if not inspector.has_table('business_profile'):
        op.create_table('business_profile',
        sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('business_name', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
        sa.Column('phone', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
        sa.Column('tax_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
        sa.Column('address', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
        sa.Column('message', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
        sa.Column('updated_at', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
        sa.CheckConstraint('id = 1', name=op.f('business_profile_id_check')),
        sa.PrimaryKeyConstraint('id', name=op.f('business_profile_pkey'))
        )
    # ### end Alembic commands ###
